### ISSUE TITLE
Q: SSR or SSG?

### ISSUE THREAD

**Issue by JustinTBrown** [Evavic44/sanity-nextjs-site#4]
Thanks for this tutorial! I really enjoyed doing it. 👍 

Something that isn't clear: what rendering strategy is being used? Static? Server-side? Since `getStaticProps` or `getServerSideProps` isn't being used, it isn't clear to me.

**Comment by Evavic44** [comment]
Hello, @JustinTBrown Happy to hear you enjoyed the article.

I used Nextjs 13 in this tutorial which introduced [server and client components](https://nextjs.org/docs/app/building-your-application/rendering); a completely different strategy for rendering React components. Server components are rendered on the server (at request or build time) and client components are rendered on the client at request time.


So to answer your question, the strategy used in this tutorial is [Static Rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#static-rendering-default), which is the default in server components

Also with nextjs 13, fetching is built into the server components which removes the need to

**Comment by Evavic44** [comment]
Hello, @JustinTBrown Happy to hear you enjoyed the article.

I used Nextjs 13 in this tutorial which introduced [server and client components](https://nextjs.org/docs/app/building-your-application/rendering); a completely different strategy for rendering React components. Server components are rendered on the server (at request or build time) and client components are rendered on the client at request time.

By default, all components are server components in nextjs 13, so rendering is done using [Static Rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#static-rendering-default), and the benefit of server components is that they are [extended with the fetch keyword](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-fetch) which allows fetching to be done simply by marking the component with `async/await`. In essence, no need to specify the `getStaticProps` or `getServerSideProps` functions anymore.

**Comment by JustinTBrown** [comment]
That makes sense. Thanks @Evavic44!

I had recently gone through the [How Next.js Works](https://nextjs.org/learn/foundations/how-nextjs-works/rendering) resource on the Next.js site which I think was written when server and client components were still in alpha. I hadn't realized there were new rendering strategies!

**Comment by Evavic44** [comment]
That's okay. 👍
